Cria artefatos
Interacao-Humano-Computador/2023.1-DetranGO pull request #114
Opened 2023-07-03 02:03 UTC by amanda-noda

| Issue |
|:-----:|
|fixes #|

# Pull Request

## 📖Cria artefatos de storyboard, protótipo de papel e protótipo de alta fidelidade

Cria artefatos de storyboard, protótipo de papel e protótipo de alta fidelidade
adiciona storyboard de consulta de veículo que estava com o fluxo de tarefa incorreto na implementação.

### 🎫 Issues

## 👩‍💻 Revisor(es)

@Carlos-E-Souza

2023-07-03 12:30 UTC, PedroFMuniz requested changes
Necessárias algumas mudanças

2023-07-03 12:30 UTC, PedroFMuniz commented on docs/design_avaliacao/nivel1/storyboards/storyboard.md
> +76
Retirar este 76

2023-07-03 12:30 UTC, PedroFMuniz commented on docs/design_avaliacao/nivel1/storyboards/storyboard.md
> +Storyboard onde retrata a jornada ddo usuário ao solicitar a segunda via da CNH no Detran GO.
Letra d duplicada

2023-07-03 12:30 UTC, PedroFMuniz commented on docs/design_avaliacao/nivel1/storyboards/storyboard.md
> +Storyboard retrata a jornada do usuário ao emitir o CRLV dentro do site do Detran GO.
Adicionar chamada da figura, por exemplo: A figura 5 apresenta o storyboard que representa...

2023-07-03 12:30 UTC, PedroFMuniz commented on docs/design_avaliacao/nivel2/prototipoPapel/prototipoPapel.md
Adicionar chamada no texto para as figuras dos protótipos

2023-07-03 12:30 UTC, PedroFMuniz commented on docs/design_avaliacao/nivel3/prototipoAlta/prototipoAlta.md
> +Para a elaboração do protótipo de alta fidelidade, foi utilizado o software Figma afim de crair os elementos gráficos do mesmo, abiaxo se encontra o protótipo desenvolvido.
Criar

2023-07-03 12:30 UTC, PedroFMuniz commented on docs/design_avaliacao/nivel3/prototipoAlta/prototipoAlta.md
Seria legal colocar prints das telas assim como no de papel

2023-07-03 12:31 UTC, Carlos-E-Souza requested changes
Review para todos os artefatos: adicionar a tag  <center></center> para centralizar as legendas das figuras

2023-07-03 12:31 UTC, Carlos-E-Souza commented on docs/design_avaliacao/nivel1/storyboards/storyboard.md
> +
Todos os storyboards estão com a mesma legenda e também é preciso chamar as figuras no texto

2023-07-03 12:31 UTC, Carlos-E-Souza commented on docs/design_avaliacao/nivel1/storyboards/storyboard.md
> +76
76 ?

2023-07-03 12:31 UTC, Carlos-E-Souza commented on docs/design_avaliacao/nivel1/storyboards/storyboard.md
> +> [5] OBS, acesso em: 27 de maio de 2023. Para mais informações acesse: [link](https://obsproject.com/pt-br/download/).
CamScanner e OBS não são referências bibliográficas

2023-07-03 12:31 UTC, Carlos-E-Souza commented on docs/design_avaliacao/nivel2/prototipoPapel/prototipoPapel.md
> +
É preciso chamar as figuras em texto

2023-07-03 12:31 UTC, Carlos-E-Souza commented on docs/design_avaliacao/nivel2/prototipoPapel/prototipoPapel.md
> +
CamScanner e OBS não são referências bibliográficas

2023-07-03 12:31 UTC, Carlos-E-Souza commented on docs/design_avaliacao/nivel3/prototipoAlta/prototipoAlta.md
> +
CamScanner e OBS não são referências bibliográficas, acredito que o relato dos resultados do storyboard também não faz sentido aqui.

2023-07-03 12:31 UTC, Carlos-E-Souza commented on docs/design_avaliacao/nivel3/prototipoAlta/prototipoAlta.md
> +| `1.0`  | 19/05/23 | Criação do documento e adição do conteúdo | Amanda N. | Carlos E. |
Data da versão errada

2023-07-04 02:54 UTC, amanda-noda commented
correções realizadas, verificar novamente por favor

2023-07-04 11:06 UTC, PedroFMuniz approved these changes
LGTM

2023-07-04 11:07 UTC, merged