Perfil usuario
Interacao-Humano-Computador/2023.1-DetranGO pull request #45
Opened 2023-05-04 19:35 UTC by amanda-noda

| Issue |
|:-----:|
|fixes #34 |

# Pull Request

## 📖 Cria Perfil de Usuário

### 🎫 Issues

## 👩‍💻 Revisor(es)

2023-05-06 00:23 UTC, phmelosilva requested changes
Modificar na linha 154 do documento de perfilUsuario.md, colatadas para coletadas. 
De resto, LGTM

2023-05-06 00:23 UTC, phmelosilva requested changes
Modificar na linha 154 do documento de perfilUsuario.md, colatadas para coletadas. 
De resto, LGTM

2023-05-06 02:30 UTC, amanda-noda commented
Foi corrigido o erro de acordo com o feedback do revisor

2023-05-08 02:14 UTC, phmelosilva approved these changes
LGTM

2023-05-08 02:14 UTC, merged