Metas de usabilidade do projeto
Interacao-Humano-Computador/2023.1-DetranGO pull request #62
Opened 2023-05-11 20:45 UTC by amanda-noda

| Issue |
|:-----:|
|fixes #56 |

# Pull Request

## 📖 Cria Metas de usabilidade do projeto 

### 🎫 Issues

## 👩‍💻 Revisor(es)

2023-05-11 22:59 UTC, phmelosilva approved these changes
LGTM

2023-05-12 01:49 UTC, MastroCoder requested changes
# Mudanças necessárias

É só um comentário. Uma coisinha.

2023-05-12 01:49 UTC, MastroCoder commented on docs/analise_requisitos/metas_de_usabilidade.md
> +As metas de usabilidade envolve definir fatores de qualidade de uso que devem ser priorizados em um projeto, como serão avaliados ao longo do processo de design, e quais faixas de valores são inaceit
Literalmente só colocar um M ali, é até chato reclamar. De resto, LGTM

2023-05-12 18:14 UTC, MastroCoder approved these changes
LGTM

2023-05-12 18:14 UTC, merged